### ISSUE TITLE
Date Modified has an A11Y error. 

### ISSUE THREAD

**Issue by shewood** [MTS-STM/DTS-Scheduler#100]
**Description of the bug**
Date Modified has an a11y error. 
run build
run a11y tests - axe
notice that there is an error 

Issue description
Ensures all page content is contained by landmarks
Element location
html
Element source
<html lang="en">
Related node:
.outer-container > .page--container

**Expected behavior**
Passes A11Y testing. 

.

**Comment by MarcoGoC** [comment]
Sheila has updated the code. 
moved the date to inside the Footer tag
