### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG 

### ISSUE THREAD

**Issue by P0NDER0SA** [MTS-STM/DTS-Scheduler#101]
**Description of the bug**
When in firefox and hitting the button on the form, it throws this error:
SSL_ERROR_RX_RECORD_TOO_LONG 
https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?as=u&utm_source=inproduct

**Expected behavior**
it does not throw that error and moves to the next page :D

.

**Comment by P0NDER0SA** [comment]
we will set upgradeInsecureRequests to FALSE in the mean time until CDS has an answer on this.  it's an ongoing issue that they are aware of

**Comment by MarcoGoC** [comment]
changed config/csp.config.js according to CDS code send by Eric
